#### from llama-factory.examples.qwen2.5_lora_pt_eval.yaml ####
### model after CPT
#model_name_or_path: /data1/model/hub/Qwen/Qwen2___5-0___5B
model_name_or_path: models/CPT/qwen2.5_0.5b_ipc_wudao65k_patentCN7w
#adapter_name_or_path: saves/IWP_instruct/lora/sft/QA_ITech_300

### model after SFT
#model_name_or_path: models/CPT/qwen2.5_3b_ipc
#adapter_name_or_path: saves/qwen2.5_3b/lora/sft/QA_IPC_des/checkpoint-100

### method
#finetuning_type: lora

### dataset
#dataset: test_demo
task: cmmlu_test # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: zh
n_shot: 5

### output
save_dir: saves/IWP_instruct/predict/IWP/cmmlu_test
#overwrite_save_dir: true
cache_dir: /data/cache

### eval
batch_size: 8 # mmlu_test 需要调4
