## Configuration for sft ##
### model
model_name_or_path: path/to/your/model

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05

### dataset
dataset: sft_datasets
template: default
cutoff_len: 512
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves_dir/of/results

logging_steps: 10
save_steps: 20
plot_loss: true
cache_dir: /path/to/cache
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 7.0e-5
num_train_epochs: 15.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 30
